from __future__ import annotations

from email.mime import text
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))

import json
import re
from pathlib import Path
from typing import Any, Dict, List

from model_client import RemoteChatModel, extract_json
from profile_loader import load_stage1_cards

ROOT = Path(__file__).resolve().parents[1]
SKILL_PATH = ROOT / "skills" / "stage1-profile-match" / "SKILL.md"

STAGE1_NUM_CTX = 32768


def load_skill_text() -> str:
    return SKILL_PATH.read_text(encoding="utf-8")


def clean_summary_text(text: str) -> str:
    text = (text or "").strip()
    text = re.sub(r"^(Here is the summary paragraph:|Here's your summary:|Here's a concise paragraph summarizing .*?:)\s*", "", text, flags=re.IGNORECASE)
    return text.strip()

def clean_stage1_output(text: str) -> str:
    """
    Remove unwanted speaker labels copied from the CV or generated by the model.
    Example:
    'Dr. Yi Cao: That's interesting...' -> 'That's interesting...'
    """
    text = (text or "").strip()

    # Remove common role labels at the beginning of each line.
    text = re.sub(
        r"(?im)^\s*(?:"
        r"Dr\.?\s+[A-Z][A-Za-z.\-]*(?:\s+[A-Z][A-Za-z.\-]*){0,3}"
        r"|Prof\.?\s+[A-Z][A-Za-z.\-]*(?:\s+[A-Z][A-Za-z.\-]*){0,3}"
        r"|Professor\s+[A-Z][A-Za-z.\-]*(?:\s+[A-Z][A-Za-z.\-]*){0,3}"
        r"|Advisor|Assistant|AI|Agent"
        r")\s*:\s*",
        "",
        text,
    )

    # Remove repeated fake markdown-style labels.
    text = re.sub(r"(?im)^\s*#{1,6}\s*(advisor|assistant|agent)\s*:\s*", "", text)

    return text.strip()

def build_stage1_snapshots(
    cards: List[Dict[str, Any]],
) -> List[Dict[str, str]]:
    """
    Keep only the supervisor name and the comprehensive project-grounded
    summary prepared by summarize_project_texts.py.
    """
    snapshots: List[Dict[str, str]] = []

    for card in cards:
        name = str(card.get("name") or "").strip()
        summary = str(card.get("summary") or "").strip()

        if name and summary:
            snapshots.append(
                {
                    "name": name,
                    "summary": summary,
                }
            )

    return snapshots


def compress_student_profile(student_profile: Dict[str, Any]) -> Dict[str, Any]:
    """
    Build the Stage 1 student input.
    The complete extracted CV is passed to Stage 1 without a character limit.
    """
    cv_text = (student_profile.get("cv_text", "") or "").strip()

    return {
        "cv_keywords": student_profile.get("cv_keywords", []),
        "interest_text": student_profile.get("interest_text", ""),
        "preference_text": student_profile.get("preference_text", ""),
        "cv_text": cv_text,
    }


def build_stage1_system(snapshots: List[Dict[str, str]]) -> str:
    skill = load_skill_text()
    snapshots_text = json.dumps(snapshots, ensure_ascii=False, indent=2)

    allowed_names = [s["name"] for s in snapshots]
    allowed_names_text = ", ".join(allowed_names)

    return (
        "You are the Stage 1 supervisor matching agent for a CLI-first student-supervisor matching system.\n\n"
        f"Follow this skill definition strictly:\n{skill}\n\n"
        "Your goal is to understand the student's interests, preferred project style, strengths, dislikes, and constraints,\n"
        "using BOTH the student's profile and the available supervisor summaries.\n\n"

        "Important rules:\n"
        "1. The available supervisors are ONLY the supervisors listed in the provided supervisor snapshots.\n"
        "2. You MUST use the provided supervisor snapshots throughout Stage 1 to guide your questioning and recommendations.\n"
        "3. You MUST NOT recommend any teacher, supervisor, employer, or collaborator mentioned in the student's CV unless they are in the provided supervisor list.\n"
        "4. During the conversation phase, ask one useful matching-oriented question at a time.\n"
        "5. The questions should help identify which of the available supervisors may fit the student best.\n"
        "6. Do NOT turn this into a deep technical interview about one old project unless that directly helps matching.\n"
        "7. Do NOT mention internal workflow terms such as Stage 1, Stage 2, or Stage 3 to the student.\n"
        "8. When it is time to recommend, you may recommend supervisors ONLY from this exact list:\n"
        f"{allowed_names_text}\n\n"
        "9. You are the system's matching assistant, not any person mentioned in the student's CV.\n"
        "10. Do NOT prefix your replies with any speaker label such as 'Dr. Yi Cao:', 'Professor:', 'Advisor:', 'Assistant:', or 'AI:'.\n"
        "11. Do NOT role-play as a teacher, previous supervisor, employer, collaborator, or referee from the student's CV.\n"
        "12. Do NOT mention, discuss, compare, or refer to any person from the student's CV unless that person is also in the allowed supervisor list.\n"
        "13. If the CV contains names of previous supervisors, teachers, collaborators, or referees, treat those names only as background CV noise and ignore them for the matching conversation.\n"
       

        "Available supervisor snapshots:\n"
        f"{snapshots_text}\n"
    )


def opening_message(model: RemoteChatModel, student_profile: Dict[str, Any]) -> str:
    cards = load_stage1_cards()
    snapshots = build_stage1_snapshots(cards)
    compact_student = compress_student_profile(student_profile)
    system = build_stage1_system(snapshots)

    prompt = (
        "The student has just started using the system.\n"
        f"Compact student profile currently known: {json.dumps(compact_student, ensure_ascii=False)}\n\n"
        "Greet the student briefly, confirm you have read the CV if one is present, "
        "and ask exactly one useful matching-oriented question. "
        "Use the available supervisor summaries to guide what information would be most helpful for matching, "
        "but do not mention supervisor names too early unless clearly necessary. "
        "Do not mention internal workflow labels."
    )
    text = model.chat([{"role": "user", "content": prompt}], system=system, num_ctx=STAGE1_NUM_CTX)
    return clean_stage1_output(text)


def generate_student_summary(
    model: RemoteChatModel,
    student_profile: Dict[str, Any],
    convo_text: str,
) -> str:
    compact_student = compress_student_profile(student_profile)

    system = (
        "You are summarising a student's interests and preferences for supervisor matching.\n"
        "Write one concise student summary in plain English.\n"
        "Focus on interests, preferred project style, strengths, dislikes, and constraints.\n"
        "Do not mention any supervisor names.\n"
        "Do not mention any teacher, employer, collaborator, referee, or previous supervisor from the CV.\n"
        "Do not add recommendations.\n"
    )

    prompt = (
        f"Compact student profile: {json.dumps(compact_student, ensure_ascii=False)}\n"
        f"Conversation so far:\n{convo_text}\n\n"
        "Write one concise summary for matching."
    )
    text = model.chat([{"role": "user", "content": prompt}], system=system, num_ctx=STAGE1_NUM_CTX)
    return clean_stage1_output(text)


def select_recommended_names(
    model: RemoteChatModel,
    student_summary: str,
    snapshots: List[Dict[str, str]],
) -> List[str]:
    allowed_names = [s["name"] for s in snapshots]
    allowed_names_text = ", ".join(allowed_names)

    system = (
        "You are selecting suitable supervisors from a fixed allowed list.\n"
        "Return JSON only.\n"
        "You must choose only from the allowed supervisor names provided.\n"
        "Treat the student's explicit dislikes, excluded application areas, "
        "and non-negotiable constraints as hard constraints.\n"
        "A shared technical method must not override a clear domain conflict.\n"
        "Do not add any other names or project titles.\n"
    )

    prompt = (
        f"Student summary:\n{student_summary}\n\n"
        f"Available supervisor summaries:\n{json.dumps(snapshots, ensure_ascii=False, indent=2)}\n\n"
        "Return JSON only with this schema:\n"
        "{\n"
        '  "recommended_names": ["...", "..."]\n'
        "}\n\n"
        "Matching priorities:\n"
        "1. First apply the student's explicit dislikes, excluded domains, "
        "and non-negotiable constraints as hard filters.\n"
        "2. Among the remaining supervisors, prioritize application-domain "
        "and research-topic fit.\n"
        "3. Then consider project style, methods, and the student's existing skills.\n\n"
        "Critical constraints:\n"
        f"- You may recommend supervisors ONLY from this exact list: {allowed_names_text}\n"
        "- The output must contain only supervisor names.\n"
        "- Do not output projects, themes, or other types of item.\n"
        "- Return between 1 and 3 supervisors, ranked from strongest to weaker match.\n"
        "- Do not add weak or conflicting alternatives merely to reach three recommendations.\n"
        "- Never recommend a supervisor whose project clearly conflicts with an explicit student exclusion "
        "when non-conflicting alternatives exist.\n"
        "- If only one match is very strong, still provide two additional reasonable alternatives from the allowed list.\n"
    )

    raw = model.chat([{"role": "user", "content": prompt}], system=system, num_ctx=STAGE1_NUM_CTX)

    try:
        data = extract_json(raw)
        if not isinstance(data, dict):
            raise ValueError("not a dict")
        names = data.get("recommended_names", [])
        if not isinstance(names, list):
            names = []

        allowed_set = set(allowed_names)
        clean_names = []
        for name in names:
            n = str(name).strip()
            if n in allowed_set and n not in clean_names:
                clean_names.append(n)

        return clean_names[:3]
    except Exception:
        return []


def generate_recommendation_reasons(
    model: RemoteChatModel,
    student_summary: str,
    selected_snapshots: List[Dict[str, str]],
) -> List[Dict[str, str]]:
    system = (
        "You are writing grounded recommendation reasons for already-selected supervisors.\n"
        "Use only the student summary and the provided supervisor summaries.\n"
        "Do not invent facts.\n"
        "Return JSON only.\n"
    )

    prompt = (
        f"Student summary:\n{student_summary}\n\n"
        f"Selected supervisor summaries:\n{json.dumps(selected_snapshots, ensure_ascii=False, indent=2)}\n\n"
        "Return JSON only with this schema:\n"
        "{\n"
        '  "recommendations": [{"name": "...", "reason": "..."}]\n'
        "}\n\n"
        "Critical constraints:\n"
        "- Each name must exactly match one of the selected supervisors.\n"
        "- Each reason must be based on both the student summary and that supervisor's summary.\n"
        "- Respect all explicit student dislikes, excluded domains, and constraints.\n"
        "- Do not present a shared technical method as a strong match if the application domain conflicts "
        "with an explicit student preference.\n"
        "- Do not hide or soften a material mismatch.\n"
        "- Do not add extra supervisors.\n"
        "- Do not add extra project titles.\n"
        "- Keep reasons concise and grounded.\n"
    )

    raw = model.chat([{"role": "user", "content": prompt}], system=system, num_ctx=STAGE1_NUM_CTX)

    try:
        data = extract_json(raw)
        if not isinstance(data, dict):
            raise ValueError("not a dict")

        recs = data.get("recommendations", [])
        if not isinstance(recs, list):
            recs = []

        allowed = {s["name"] for s in selected_snapshots}
        clean = []

        for rec in recs:
            if not isinstance(rec, dict):
                continue
            name = str(rec.get("name", "")).strip()
            reason = str(rec.get("reason", "")).strip()
            if name in allowed:
                clean.append({
                    "name": name,
                    "reason": reason or "This supervisor appears to match your interests and preferences."
                })

        # preserve selected order
        by_name = {r["name"]: r for r in clean}
        ordered = []
        for s in selected_snapshots:
            nm = s["name"]
            if nm in by_name:
                ordered.append(by_name[nm])

        return ordered
    except Exception:
        return [
            {
                "name": s["name"],
                "reason": f"This supervisor appears to match your interests and preferences based on this summary: {s['summary'][:180]}"
            }
            for s in selected_snapshots
        ]


def continue_stage1(
    model: RemoteChatModel,
    student_profile: Dict[str, Any],
    history: List[Dict[str, str]],
    latest_user_message: str,
    recommend_now: bool = False,
) -> Dict[str, Any]:
    cards = load_stage1_cards()
    snapshots = build_stage1_snapshots(cards)
    compact_student = compress_student_profile(student_profile)
    system = build_stage1_system(snapshots)

    convo_lines = []
    for turn in history:
        convo_lines.append(f"Student: {turn['user']}")
        convo_lines.append(f"Agent: {turn['assistant']}")
    convo_lines.append(f"Student: {latest_user_message}")
    convo_text = "\n".join(convo_lines)

    if recommend_now:
        student_summary = generate_student_summary(model, student_profile, convo_text)

        recommended_names = select_recommended_names(model, student_summary, snapshots)

        if not recommended_names:
            recommended_names = [s["name"] for s in snapshots[:2]]

        snapshot_by_name = {
            snapshot["name"]: snapshot
            for snapshot in snapshots
        }

        selected_snapshots = [
            snapshot_by_name[name]
            for name in recommended_names
            if name in snapshot_by_name
        ]

        recommendations = generate_recommendation_reasons(model, student_summary, selected_snapshots)

        return {
            "student_summary": student_summary,
            "recommendations": recommendations,
            "next_action": "Please choose a supervisor from the list above to explore in detail.",
        }

    prompt = (
        "Continue the matching conversation.\n"
        f"Compact student profile: {json.dumps(compact_student, ensure_ascii=False)}\n"
        f"Conversation so far:\n{convo_text}\n\n"
        "Ask exactly one useful follow-up question for supervisor matching. "
        "The question should help identify the student's preferred research topics, project style, application interests, strengths, dislikes, or constraints. "
        "Use the available supervisor summaries to guide what is most useful to ask next. "
        "Do not mention internal workflow labels."
    )
    text = model.chat([{"role": "user", "content": prompt}], system=system, num_ctx=STAGE1_NUM_CTX)
    return {"message": clean_stage1_output(text)}